openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /user/{username}/repositories:
    get:
      tags:
        - user-repositories-controller
      operationId: repositories
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'
    x-amazon-apigateway-integration:
      payloadFormatVersion: "1.0"
      type: "http_proxy"
      httpMethod: "GET"
      uri:
        Fn::Sub: "arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:listener/app/tuicodechallengeLoadBalancer/${LoadBalancer.Arn}/${ListenerHTTP.ListenerArn}"
      connectionType: "VPC_LINK"
components:
  schemas:
    Branch:
      type: object
      properties:
        branchName:
          type: string
        lastCommitSha:
          type: string
    Repository:
      type: object
      properties:
        repositoryName:
          type: string
        ownerLogin:
          type: string
        branchList:
          type: array
          items:
            $ref: '#/components/schemas/Branch'
